export const FETCH_PRODUCT_REQUEST='FETCH_PRODUCT_REQUEST'
export const FETCH_PRODUCT_SUCCESS='FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_FAILURE='FETCH_PRODUCT_FAILURE'


export const POST_PRODUCT_REQUEST='POST_PRODUCT_REQUEST'
export const POST_PRODUCT_SUCCESS='POST_PRODUCT_SUCCESS'
export const POST_PRODUCT_FAILURE='POST_PRODUCT_FAILURE'


export const PUT_PRODUCT_REQUEST='PUT_PRODUCT_REQUEST'
export const PUT_PRODUCT_SUCCESS='PUT_PRODUCT_SUCCESS'
export const PUT_PRODUCT_FAILURE='PUT_PRODUCT_FAILURE'


export const REQUEST_SUCCESS='REQUEST_SUCCESS'
export const REQUEST_FAILURE='REQUEST_FAILURE'
