export const FETCH_RECEIPT_REQUEST='FETCH_RECEIPT_REQUEST'
export const FETCH_RECEIPT_SUCCESS='FETCH_RECEIPT_SUCCESS'
export const FETCH_RECEIPT_FAILURE='FETCH_RECEIPT_FAILURE'

export const FETCH_RANDOM_REQUEST='FETCH_RANDOM_REQUEST'
export const FETCH_RANDOM_SUCCESS='FETCH_RANDOM_SUCCESS'
export const FETCH_RANDOM_FAILURE='FETCH_RANDOM_FAILURE'